### ISSUE TITLE
Configure which tag to show for terminals

### ISSUE THREAD

**Issue by ssiccha** [ldelossa/buffertag#11]
First of all, thanks for the cool plugin!

I have a neovim terminal buffer and I would like to let the `buffertag` show the output of the `echo &channel`. Is there an option to customize buffertag that way?

**Comment by ldelossa** [comment]
Hey. Usually, we dont render for terminals, but maybe we can give it a shot. 

What does "echo &channel" typically display?

**Comment by ssiccha** [comment]
It's typically an integer. See the [neovim docs channel](https://neovim.io/doc/user/channel.html) for what it represents.  I'm not sure whether `echo &channel` is useful for everyone, hence the ask to maybe make it configurable what's displayed for terminals.

**Comment by ldelossa** [comment]
Yeah I cant really see any use for this in the general sense. 

Buffertag is going to remain pretty opinionated and "dumb" with as little config as possible. 

If youre looking for more customization I would recommend: 

https://github.com/b0o/incline.nvim
