### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by jackfranklin** [ldelossa/buffertag#5]
Hello,

Would you consider adding a LICENSE to this repository to make the usage terms clear?

As far as I understand the MIT License is a sensible default (and what other plugins such as [telescope](https://github.com/nvim-telescope/telescope.nvim/blob/master/LICENSE)) use, but as the author and owner that's entirely your choice :)

Thanks!

**Comment by ldelossa** [comment]
Doh! you are right. Will do this now.

**Comment by ldelossa** [comment]
Done

**Comment by jackfranklin** [comment]
Awesome, thanks!
