### ISSUE TITLE
React to window resize event

### ISSUE THREAD

**Issue by jackfranklin** [ldelossa/buffertag#8]
If I have a buffertag displaying for window X, but then resize the window, the buffertag's position isn't redrawn and ends up looking a little off:

Before resize, in correct position:
<img width="733" alt="Screenshot 2022-08-20 at 10 24 11" src="https://user-images.githubusercontent.com/193238/185759133-d59e6fd7-2330-40c9-8291-8baab87929e6.png">

After resize:
<img width="756" alt="Screenshot 2022-08-20 at 10 24 16" src="https://user-images.githubusercontent.com/193238/185759139-a020e934-e6db-4895-b7d6-5c14248bd173.png">

I think we can listen to a resize event/autocmd and re-draw the buffertag. Would you be open to a PR that does that?

**Comment by ldelossa** [comment]
Hey there! 

I did try this! And for some reason i didnt get it to work. If you submit a PR for this id definitely accept

**Comment by ldelossa** [comment]
P.s - i dig your nice white theme. White themes are underrated!

**Comment by trmckay** [comment]
~Until something like https://github.com/neovim/neovim/issues/11532, I don't know if it's possible to fix this.~

jk -- https://github.com/ldelossa/buffertag/pull/10
